[package]
name = "system-monitor"
version = "0.1.0"
authors = ["Isabelle <patchydev@proton.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.35.0"
